// lib/widgets/sign_avatar_widget.dart
//
// Draws and animates a hand skeleton for a given English sign word.
// Data source: assets/sign_data.json (generated by extract_keypoints.py)
// NEW file — does NOT touch any existing files.

import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

// ── Data model ────────────────────────────────────────────────────────────────

class _Landmark {
  final int    id;
  final double x, y, z;
  const _Landmark({required this.id, required this.x,
                   required this.y,  required this.z});

  factory _Landmark.fromJson(Map<String, dynamic> j) => _Landmark(
        id: j['id'] as int,
        x:  (j['x'] as num).toDouble(),
        y:  (j['y'] as num).toDouble(),
        z:  (j['z'] as num).toDouble(),
      );
}

class _SignData {
  final List<List<_Landmark>> frames;   // 30 frames × 21 landmarks
  final int                   durationMs;
  final int                   frameCount;

  const _SignData({
    required this.frames,
    required this.durationMs,
    required this.frameCount,
  });

  factory _SignData.fromJson(Map<String, dynamic> j) {
    final rawFrames = j['frames'] as List<dynamic>;
    final frames = rawFrames.map((f) {
      final lms = (f['landmarks'] as List<dynamic>)
          .map((l) => _Landmark.fromJson(l as Map<String, dynamic>))
          .toList();
      return lms;
    }).toList();

    return _SignData(
      frames:     frames,
      durationMs: j['duration_ms'] as int,
      frameCount: j['frame_count'] as int,
    );
  }

  // Milliseconds per frame at 1x speed
  int get msPerFrame => (durationMs / frameCount).round().clamp(33, 500);
}

// ── Hand skeleton connections ─────────────────────────────────────────────────

const List<List<int>> _kConnections = [
  [0, 1], [1, 2], [2, 3], [3, 4],           // Thumb
  [0, 5], [5, 6], [6, 7], [7, 8],           // Index
  [0, 9], [9, 10], [10, 11], [11, 12],      // Middle
  [0, 13], [13, 14], [14, 15], [15, 16],    // Ring
  [0, 17], [17, 18], [18, 19], [19, 20],    // Pinky
  [5, 9], [9, 13], [13, 17],                // Palm
];

// ── CustomPainter ─────────────────────────────────────────────────────────────

class _HandPainter extends CustomPainter {
  final List<_Landmark> landmarks;

  const _HandPainter({required this.landmarks});

  @override
  void paint(Canvas canvas, Size size) {
    if (landmarks.isEmpty) return;

    final linePaint = Paint()
      ..color       = Colors.white.withOpacity(0.8)
      ..strokeWidth = 3.0
      ..strokeCap   = StrokeCap.round;

    final jointPaint = Paint()
      ..color = const Color(0xFF7C3AED);

    // Convert normalised (0-1) coords to canvas pixels
    Offset toOffset(_Landmark lm) =>
        Offset(lm.x * size.width, lm.y * size.height);

    // Draw connections
    for (final conn in _kConnections) {
      final a = landmarks[conn[0]];
      final b = landmarks[conn[1]];
      canvas.drawLine(toOffset(a), toOffset(b), linePaint);
    }

    // Draw joints on top of lines
    for (final lm in landmarks) {
      canvas.drawCircle(toOffset(lm), 5.0, jointPaint);
    }
  }

  @override
  bool shouldRepaint(_HandPainter old) => old.landmarks != landmarks;
}

// ── Main widget ───────────────────────────────────────────────────────────────

class SignAvatarWidget extends StatefulWidget {
  final String signWord; // English word or phrase, e.g. "Book"

  const SignAvatarWidget({
    Key?         key,
    required this.signWord,
  }) : super(key: key);

  @override
  State<SignAvatarWidget> createState() => _SignAvatarWidgetState();
}

class _SignAvatarWidgetState extends State<SignAvatarWidget> {
  // Loading state
  bool      _loading   = true;
  String?   _error;
  _SignData? _signData;

  // Playback state
  int    _currentFrame = 0;
  bool   _playing      = true;
  double _speed        = 1.0;   // 0.25 | 0.5 | 0.75 | 1.0
  Timer? _timer;

  @override
  void initState() {
    super.initState();
    _loadSign();
  }

  @override
  void didUpdateWidget(SignAvatarWidget old) {
    super.didUpdateWidget(old);
    if (old.signWord != widget.signWord) {
      _stopTimer();
      setState(() {
        _loading      = true;
        _error        = null;
        _signData     = null;
        _currentFrame = 0;
        _playing      = true;
      });
      _loadSign();
    }
  }

  @override
  void dispose() {
    _stopTimer();
    super.dispose();
  }

  // ── Data loading ────────────────────────────────────────────────

  Future<void> _loadSign() async {
    try {
      final raw   = await rootBundle.loadString('assets/sign_data.json');
      final json  = jsonDecode(raw) as Map<String, dynamic>;
      final signs = json['signs'] as Map<String, dynamic>;

      // Case-insensitive lookup
      final key = signs.keys.firstWhere(
        (k) => k.toLowerCase() == widget.signWord.toLowerCase(),
        orElse: () => '',
      );

      if (key.isEmpty) {
        setState(() {
          _loading = false;
          _error   = 'Sign not available yet\n"${widget.signWord}"';
        });
        return;
      }

      final data = _SignData.fromJson(signs[key] as Map<String, dynamic>);
      setState(() {
        _signData = data;
        _loading  = false;
      });

      if (_playing) _startTimer();
    } catch (e) {
      setState(() {
        _loading = false;
        _error   = 'Failed to load sign data: $e';
      });
    }
  }

  // ── Animation timer ─────────────────────────────────────────────

  void _startTimer() {
    _stopTimer();
    if (_signData == null) return;
    final interval = (_signData!.msPerFrame / _speed).round();
    _timer = Timer.periodic(Duration(milliseconds: interval), (_) {
      if (!mounted) return;
      setState(() {
        _currentFrame = (_currentFrame + 1) % _signData!.frames.length;
      });
    });
  }

  void _stopTimer() {
    _timer?.cancel();
    _timer = null;
  }

  void _togglePlayPause() {
    setState(() => _playing = !_playing);
    if (_playing) {
      _startTimer();
    } else {
      _stopTimer();
    }
  }

  void _setSpeed(double s) {
    setState(() => _speed = s);
    if (_playing) _startTimer();
  }

  // ── Build ────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    if (_loading) return _buildLoading();
    if (_error != null) return _buildError();
    return _buildPlayer();
  }

  Widget _buildLoading() => const SizedBox(
        height: 280,
        child: Center(
          child: CircularProgressIndicator(
            color      : Color(0xFF7B2FBE),
            strokeWidth: 2.5,
          ),
        ),
      );

  Widget _buildError() => SizedBox(
        height: 120,
        child: Center(
          child: Text(
            _error!,
            textAlign: TextAlign.center,
            style: TextStyle(
              color   : Colors.white.withOpacity(0.45),
              fontSize: 13,
            ),
          ),
        ),
      );

  Widget _buildPlayer() {
    final sign  = _signData!;
    final frame = sign.frames[_currentFrame];
    final total = sign.frames.length;

    return Column(
      children: [
        // ── Sign name label ──────────────────────────────────────
        Padding(
          padding: const EdgeInsets.only(bottom: 8),
          child: Text(
            widget.signWord,
            style: const TextStyle(
              color       : Color(0xFFCB9BFF),
              fontSize    : 16,
              fontWeight  : FontWeight.w700,
              letterSpacing: 0.5,
            ),
          ),
        ),

        // ── Hand skeleton canvas ─────────────────────────────────
        Container(
          height: 240,
          margin: const EdgeInsets.symmetric(horizontal: 24),
          decoration: BoxDecoration(
            color       : Colors.white.withOpacity(0.03),
            borderRadius: BorderRadius.circular(20),
            border      : Border.all(
                color: const Color(0xFF7B2FBE).withOpacity(0.2)),
          ),
          child: ClipRRect(
            borderRadius: BorderRadius.circular(20),
            child: CustomPaint(
              painter: _HandPainter(landmarks: frame),
              size: Size.infinite,
            ),
          ),
        ),

        const SizedBox(height: 10),

        // ── Frame progress bar ───────────────────────────────────
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 24),
          child: ClipRRect(
            borderRadius: BorderRadius.circular(4),
            child: LinearProgressIndicator(
              value          : (_currentFrame + 1) / total,
              minHeight      : 3,
              backgroundColor: Colors.white12,
              valueColor     : const AlwaysStoppedAnimation<Color>(
                  Color(0xFF7B2FBE)),
            ),
          ),
        ),

        const SizedBox(height: 12),

        // ── Controls row ─────────────────────────────────────────
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 24),
          child: Row(
            children: [
              // Play / Pause button
              GestureDetector(
                onTap: _togglePlayPause,
                child: Container(
                  width : 44,
                  height: 44,
                  decoration: BoxDecoration(
                    shape : BoxShape.circle,
                    color : const Color(0xFF7B2FBE).withOpacity(0.2),
                    border: Border.all(
                        color: const Color(0xFF7B2FBE).withOpacity(0.5)),
                  ),
                  child: Icon(
                    _playing ? Icons.pause_rounded : Icons.play_arrow_rounded,
                    color: const Color(0xFFCB9BFF),
                    size : 24,
                  ),
                ),
              ),

              const SizedBox(width: 14),

              // Speed label
              Text('Speed',
                  style: TextStyle(
                      color   : Colors.white.withOpacity(0.4),
                      fontSize: 11)),

              const SizedBox(width: 8),

              // Speed slider 0.25x to 1.0x
              Expanded(
                child: SliderTheme(
                  data: SliderThemeData(
                    activeTrackColor  : const Color(0xFF7B2FBE),
                    inactiveTrackColor: Colors.white12,
                    thumbColor        : const Color(0xFFCB9BFF),
                    overlayColor      : const Color(0xFF7B2FBE).withOpacity(0.2),
                    trackHeight       : 3,
                    thumbShape: const RoundSliderThumbShape(
                        enabledThumbRadius: 7),
                  ),
                  child: Slider(
                    value    : _speed,
                    min      : 0.25,
                    max      : 1.0,
                    divisions: 3,
                    onChanged: _setSpeed,
                  ),
                ),
              ),

              // Speed value label
              SizedBox(
                width: 38,
                child: Text(
                  '${_speed}x',
                  textAlign: TextAlign.right,
                  style: const TextStyle(
                      color    : Color(0xFFCB9BFF),
                      fontSize : 11,
                      fontWeight: FontWeight.w700),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
